Update piratebox daemon for ArtBox

diff --git a/piratebox/piratebox/init.d/piratebox b/piratebox/piratebox/init.d/piratebox
--- a/piratebox/piratebox/init.d/piratebox
+++ b/piratebox/piratebox/init.d/piratebox
@@ -14,6 +14,7 @@
 ###  
 #  Default start-stop script for piratebox services on a laptop
 #   written by Matthias Strubel  (matthias.strubel@aod-rpg.de) 2011-02-22 
+#   modified for ArtBox by Brannon Dorsey (brannon@brannondorsey.com) 2015-02-22
 #  licenced by gpl, feel free to improve and send me comments
 
 . /lib/lsb/init-functions
@@ -28,11 +29,11 @@ PIDFILE_DROOPY=/var/run/piratebox_droopy.pid
 PIDFILE_HOSTAPN=/var/run/piratebox_hostapn.pid
 PIDFILE_DNSMASQ=/var/run/piratebox_dnsmasq.pid
 PIDFILE_LIGHTTPD=/opt/piratebox/tmp/lighttpd.pid
-PIDFILE_SHOUTBOX=/opt/piratebox/tmp/shoutbox_daemon.pid
+PIDFILE_ALT_WEBSERVER=/opt/piratebox/tmp/alt_webserver.pid
+# PIDFILE_SHOUTBOX=/opt/piratebox/tmp/shoutbox_daemon.pid
 
 PIRATEBOX=/opt/piratebox
 CONF=$PIRATEBOX/conf/piratebox.conf
-#CONF_DROOPY=/opt/piratebox/conf/droopy.conf #not used
 CONF_APN=$PIRATEBOX/conf/hostapd.conf
 
 #Some extra config files for dnsmasq
@@ -42,14 +43,13 @@ CONF_LIGHTTPD=$PIRATEBOX/conf/lighttpd/lighttpd.conf
 
 export PYTHONPATH=:$PYTHONPATH:$PIRATEBOX_PYTHONPATH
 
-
 # Some things that run always
 touch /var/lock/piratebox
 
 if [ -f $CONF ] ; then
    . $CONF 
 else 
-   log_failure_msg "Configuration file not found"
+   log_failure_msg "Configuration file not found in $CONF"
    exit 1
 fi
 
@@ -83,8 +83,8 @@ case "$1" in
     echo "Empty tmp folder"
     find   $PIRATEBOX/tmp/  -exec rm {} \;
 
-    echo "Copy over design files"
-    $PIRATEBOX/bin/distribute_files.sh $SHARE_FOLDER/Shared
+    #echo "Copy over design files"
+    #$PIRATEBOX/bin/distribute_files.sh $SHARE_FOLDER/Shared
 
     if [ "$DO_IW" = "yes" ] ; then
        log_daemon_msg " Setting up Interface (iw) "
@@ -108,12 +108,12 @@ case "$1" in
        fi
 
       if [ "$DO_IFCONFIG" = yes ] ; then
-	log_daemon_msg "  Setting up wlan"
+	      log_daemon_msg "  Setting up wlan"
         #Setting up WLAN Interface
         piratebox_setup_wlan.sh  $CONF start
         if  [ $? -ne 0 ] ;  then
           log_failure_msg "failed setting up Interface"
-	  exit 99
+	        exit 99
         fi
       fi
 
@@ -149,21 +149,28 @@ case "$1" in
           log_end_msg $?
        fi
 
-       #Do shoutbox stuff
-       $PIRATEBOX/bin/shoutbox_stuff.sh $WWW_FOLDER $CONF
-
+       # Do shoutbox stuff
+       # $PIRATEBOX/bin/shoutbox_stuff.sh $WWW_FOLDER $CONF
 
        #Start here the lighttpd i.e.
-       log_daemon_msg "Starting lighttpd..."
-       start-stop-daemon --start --quiet  --pidfile $PIDFILE_LIGHTTPD --exec /usr/sbin/lighttpd -- -f $CONF_LIGHTTPD
-       log_end_msg $?
+       if ["$USE_LIGHTTPD" = "yes"] ; then
+          log_daemon_msg "Starting lighttpd..."
+          start-stop-daemon --start --quiet  --pidfile $PIDFILE_LIGHTTPD --exec /usr/sbin/lighttpd -- -f $CONF_LIGHTTPD
+          log_end_msg $?
+       elif ["$ALT_WEBSERVER_EXEC" != ""]; then
+          log_daemon_msg "Starting alternative webserver..."
+          start-stop-daemon --start --quiet  --pidfile $PIDFILE_ALT_WEBSERVER --exec $ALT_WEBSERVER_EXEC -- $ALT_WEBSERVER_ARGS
+          log_daemon_msg $?
+       else
+          log_daemon_msg "Lighttpd disabled in piratebox config and no alternative webserver commands found."
+       fi
 
        #Start Global Chat daemon if needed.
-       if [ "$GLOBAL_CHAT" = "yes" ] ; then
-          log_daemon_msg "Starting global chat service..."
-          start-stop-daemon -m --start  --background --pidfile $PIDFILE_SHOUTBOX --startas $PIRATEBOX/bin/shoutbox_daemon.sh -- $CONF
-          log_end_msg $?
-       fi
+       # if [ "$GLOBAL_CHAT" = "yes" ] ; then
+       #    log_daemon_msg "Starting global chat service..."
+       #    start-stop-daemon -m --start  --background --pidfile $PIDFILE_SHOUTBOX --startas $PIRATEBOX/bin/shoutbox_daemon.sh -- $CONF
+       #    log_end_msg $?
+       # fi
      fi
 
      $PIRATEBOX/bin/hooks/hook_piratebox_start_done.sh  "$CONF"
@@ -187,15 +194,21 @@ case "$1" in
     fi
 
     #Stop Global Chat daemon
-    if [ "$GLOBAL_CHAT" = "yes" ] ; then
-          log_daemon_msg "Stopping global chat service..."
-          start-stop-daemon --stop --quiet --pidfile $PIDFILE_SHOUTBOX
-          log_end_msg $?
-    fi
+    # if [ "$GLOBAL_CHAT" = "yes" ] ; then
+    #       log_daemon_msg "Stopping global chat service..."
+    #       start-stop-daemon --stop --quiet --pidfile $PIDFILE_SHOUTBOX
+    #       log_end_msg $?
+    # fi
 
-    log_daemon_msg "Stopping lighttpd..."
-    start-stop-daemon --stop --retry 30 --quiet --pidfile $PIDFILE_LIGHTTPD
-    log_end_msg $?
+    if ["$USE_LIGHTTPD" = "yes"] ; then
+      log_daemon_msg "Stopping lighttpd..."
+      start-stop-daemon --stop --retry 30 --quiet --pidfile $PIDFILE_LIGHTTPD
+      log_end_msg $?
+    elif ["$ALT_WEBSERVER_EXEC" != ""]; then
+      log_daemon_msg "Stopping alternative webserver..."
+      start-stop-daemon --stop --retry 30 --quiet --pidfile $PIDFILE_ALT_WEBSERVER
+      log_end_msg $?
+    fi
 
     if [ "$DROOPY_ENABLED" = "yes" ] ; then
        #Kill Droopy
