Upped probing time to 30s

diff --git a/piratebox/piratebox/init.d/piratebox b/piratebox/piratebox/init.d/piratebox
--- a/piratebox/piratebox/init.d/piratebox
+++ b/piratebox/piratebox/init.d/piratebox
@@ -67,120 +67,113 @@ fi
 # Command Line for DNSMASQ,  use extra config file generated from command above
 CMD_DNSMASQ="-x $PIDFILE_DNSMASQ -C $CONF_DNSMASQ "
 
-startPiratebox() {
-  log_daemon_msg "Starting piratebox"
-  echo ""
-
-  # Generate hosts & dnsmasq file
-  $PIRATEBOX/bin/generate_config_files.sh  "$CONF"
-  
-  $PIRATEBOX/bin/hooks/hook_piratebox_start.sh  "$CONF"
-
-  echo "Empty tmp folder"
-  find   $PIRATEBOX/tmp/  -exec rm {} \;
-
-  #echo "Copy over design files"
-  #$PIRATEBOX/bin/distribute_files.sh $SHARE_FOLDER/Shared
-
-  if [ "$DO_IW" = "yes" ] ; then
-     log_daemon_msg " Setting up Interface (iw) "
-     iw $PHY_IF interface add $INTERFACE type managed
-  fi
-
-  if [ "$PROBE_INTERFACE" = yes ] ; then
-    log_daemon_msg "  Probing wlan"
-    #Setting up WLAN Interface
-    piratebox_setup_wlan.sh  $CONF probe
-  fi
-   if  [ $? -ne 0 ] ;  then
-     log_failure_msg "failed probe Interface"
-   else
-
-     # Only  activate
-     if  [ "$USE_APN" =  "yes" ] ;  then
-       log_daemon_msg  "Starting hostap... "
-       start-stop-daemon -m --start --background --pidfile $PIDFILE_HOSTAPN  --exec /usr/sbin/hostapd --  $CONF_APN
-       log_end_msg $?
-     fi
-
-    if [ "$DO_IFCONFIG" = yes ] ; then
-      log_daemon_msg "  Setting up wlan"
-      #Setting up WLAN Interface
-      piratebox_setup_wlan.sh  $CONF start
-      if  [ $? -ne 0 ] ;  then
-        log_failure_msg "failed setting up Interface"
-        exit 99
-      fi
-    fi
-
-    #BRIDGE
-    if [ "$DO_BRIDGE" = "yes"  ] ; then
-       log_daemon_msg  "Adding $INTERFACE to bridge $BRIDGE //  brctl addif $BRIDGE  $INTERFACE "
-       sleep 1
-       BR_CMD="brctl addif  $BRIDGE  $INTERFACE"
-       ( $BR_CMD ; )
-       log_end_msg $?
-    fi
-
-    if [ "$USE_DNSMASQ" = "yes" ] ;  then
-       log_daemon_msg  "Starting dnsmasq... "
-        # pidfile is written by dnsmasq
-       start-stop-daemon --start --quiet --exec /usr/sbin/dnsmasq  --  $CMD_DNSMASQ  
-       log_end_msg $?
-    fi
-
-      if [ "$DROOPY_ENABLED" = "yes" ] ; then
-        #Start here the PirateBox-Parts droopy i.e.
-        #Delete 0 Byte Files
-        delete_empty.sh  $UPLOADFOLDER
-        find  $UPLOADFOLDER/ -iname tmp\* -exec rm {} \;
-
-        DROOPY_USER=""
-        if [ "$DROOPY_USE_USER" = "yes" ] ; then
-          DROOPY_USER=" -c $LIGHTTPD_USER:$LIGHTTPD_GROUP "
-        fi
-        log_daemon_msg "Starting droopy..."
-        start-stop-daemon $DROOPY_USER -m --start --background  --pidfile $PIDFILE_DROOPY --exec $PIRATEBOX/bin/droopy -- -H $HOST -d "$UPLOADFOLDER" -c "" -m "$DROOPY_TXT" $DROOPY_USERDIR  $DROOPY_PORT
-        log_end_msg $?
-     fi
-
-     # Do shoutbox stuff
-     # $PIRATEBOX/bin/shoutbox_stuff.sh $WWW_FOLDER $CONF
-
-     #Start here the lighttpd i.e.
-     if [ "$USE_LIGHTTPD" = "yes" ] ; then
-        log_daemon_msg "Starting lighttpd..."
-        start-stop-daemon --start --quiet  --pidfile $PIDFILE_LIGHTTPD --exec /usr/sbin/lighttpd -- -f $CONF_LIGHTTPD
-        log_end_msg $?
-     elif [ "$ALT_WEBSERVER_EXEC" != "" ]; then
-        log_daemon_msg "Starting alternative webserver..."
-        start-stop-daemon --start --quiet  --pidfile $PIDFILE_ALT_WEBSERVER --exec $ALT_WEBSERVER_EXEC -- $ALT_WEBSERVER_ARGS
-        log_daemon_msg $?
-     else
-        log_daemon_msg "Lighttpd disabled in piratebox config and no alternative webserver commands found."
-     fi
-
-     #Start Global Chat daemon if needed.
-     # if [ "$GLOBAL_CHAT" = "yes" ] ; then
-     #    log_daemon_msg "Starting global chat service..."
-     #    start-stop-daemon -m --start  --background --pidfile $PIDFILE_SHOUTBOX --startas $PIRATEBOX/bin/shoutbox_daemon.sh -- $CONF
-     #    log_end_msg $?
-     # fi
-   fi
-
-   $PIRATEBOX/bin/hooks/hook_piratebox_start_done.sh  "$CONF"
-}
 
 # Carry out specific functions when asked to by the system
 case "$1" in
   start)
-    log_daemon_msg "Starting script piratebox in 30 seconds"
-    sleep 30s
-    startPiratebox
-    ;;
-  start-now)
-    startPiratebox
-    ;;
+
+    log_daemon_msg "Starting piratebox"
+    echo ""
+
+    # Generate hosts & dnsmasq file
+    $PIRATEBOX/bin/generate_config_files.sh  "$CONF"
+    
+    $PIRATEBOX/bin/hooks/hook_piratebox_start.sh  "$CONF"
+
+    echo "Empty tmp folder"
+    find   $PIRATEBOX/tmp/  -exec rm {} \;
+
+    #echo "Copy over design files"
+    #$PIRATEBOX/bin/distribute_files.sh $SHARE_FOLDER/Shared
+
+    if [ "$DO_IW" = "yes" ] ; then
+       log_daemon_msg " Setting up Interface (iw) "
+       iw $PHY_IF interface add $INTERFACE type managed
+    fi
+
+    if [ "$PROBE_INTERFACE" = yes ] ; then
+      log_daemon_msg "  Probing wlan"
+      #Setting up WLAN Interface
+      piratebox_setup_wlan.sh  $CONF probe
+    fi
+     if  [ $? -ne 0 ] ;  then
+       log_failure_msg "failed probe Interface"
+     else
+
+       # Only  activate
+       if  [ "$USE_APN" =  "yes" ] ;  then
+         log_daemon_msg  "Starting hostap... "
+         start-stop-daemon -m --start --background --pidfile $PIDFILE_HOSTAPN  --exec /usr/sbin/hostapd --  $CONF_APN
+         log_end_msg $?
+       fi
+
+      if [ "$DO_IFCONFIG" = yes ] ; then
+        log_daemon_msg "  Setting up wlan"
+        #Setting up WLAN Interface
+        piratebox_setup_wlan.sh  $CONF start
+        if  [ $? -ne 0 ] ;  then
+          log_failure_msg "failed setting up Interface"
+          exit 99
+        fi
+      fi
+
+      #BRIDGE
+      if [ "$DO_BRIDGE" = "yes"  ] ; then
+         log_daemon_msg  "Adding $INTERFACE to bridge $BRIDGE //  brctl addif $BRIDGE  $INTERFACE "
+         sleep 1
+         BR_CMD="brctl addif  $BRIDGE  $INTERFACE"
+         ( $BR_CMD ; )
+         log_end_msg $?
+      fi
+
+      if [ "$USE_DNSMASQ" = "yes" ] ;  then
+         log_daemon_msg  "Starting dnsmasq... "
+          # pidfile is written by dnsmasq
+         start-stop-daemon --start --quiet --exec /usr/sbin/dnsmasq  --  $CMD_DNSMASQ  
+         log_end_msg $?
+      fi
+
+        if [ "$DROOPY_ENABLED" = "yes" ] ; then
+          #Start here the PirateBox-Parts droopy i.e.
+          #Delete 0 Byte Files
+          delete_empty.sh  $UPLOADFOLDER
+          find  $UPLOADFOLDER/ -iname tmp\* -exec rm {} \;
+
+          DROOPY_USER=""
+          if [ "$DROOPY_USE_USER" = "yes" ] ; then
+            DROOPY_USER=" -c $LIGHTTPD_USER:$LIGHTTPD_GROUP "
+          fi
+          log_daemon_msg "Starting droopy..."
+          start-stop-daemon $DROOPY_USER -m --start --background  --pidfile $PIDFILE_DROOPY --exec $PIRATEBOX/bin/droopy -- -H $HOST -d "$UPLOADFOLDER" -c "" -m "$DROOPY_TXT" $DROOPY_USERDIR  $DROOPY_PORT
+          log_end_msg $?
+       fi
+
+       # Do shoutbox stuff
+       # $PIRATEBOX/bin/shoutbox_stuff.sh $WWW_FOLDER $CONF
+
+       #Start here the lighttpd i.e.
+       if [ "$USE_LIGHTTPD" = "yes" ] ; then
+          log_daemon_msg "Starting lighttpd..."
+          start-stop-daemon --start --quiet  --pidfile $PIDFILE_LIGHTTPD --exec /usr/sbin/lighttpd -- -f $CONF_LIGHTTPD
+          log_end_msg $?
+       elif [ "$ALT_WEBSERVER_EXEC" != "" ]; then
+          log_daemon_msg "Starting alternative webserver..."
+          start-stop-daemon --start --quiet  --pidfile $PIDFILE_ALT_WEBSERVER --exec $ALT_WEBSERVER_EXEC -- $ALT_WEBSERVER_ARGS
+          log_daemon_msg $?
+       else
+          log_daemon_msg "Lighttpd disabled in piratebox config and no alternative webserver commands found."
+       fi
+
+       #Start Global Chat daemon if needed.
+       # if [ "$GLOBAL_CHAT" = "yes" ] ; then
+       #    log_daemon_msg "Starting global chat service..."
+       #    start-stop-daemon -m --start  --background --pidfile $PIDFILE_SHOUTBOX --startas $PIRATEBOX/bin/shoutbox_daemon.sh -- $CONF
+       #    log_end_msg $?
+       # fi
+     fi
+
+     $PIRATEBOX/bin/hooks/hook_piratebox_start_done.sh  "$CONF"
+
   stop)
     log_daemon_msg  "Stopping script piratebox"
     echo ""
@@ -243,7 +236,7 @@ case "$1" in
 
     ;;
   *)
-    echo "Usage: /etc/init.d/piratebox { start | start-now | stop }"
+    echo "Usage: /etc/init.d/piratebox { start | stop }"
     exit 1
     ;;
 esac
